commit what you've made
Osselnet/gophermart pull request #1
Opened 2023-08-28 11:48 UTC by Osselnet

2023-09-04 21:29 UTC, valentinsoe requested changes
Спасибо за работу.

Отлично, что ты для все операции с БД выполняешь используя транзакции и обеспечивая целостность.

Часть комментариев написал по коду, добавлю еще:
1) Предлагаю получше разделить на компоненты код. Например клиент внешнего сервиса должен уметь только делать запросы к внешнему сервису и не допускать избыточных запросов. А вот интерпретировать его ответы и обновлять БД - уже кусок бизнес-логики.
2) При наличии уровня бизнес-логики  у нас эта логика все равно почему-то просочилась существенно на уровень БД
3) write-through cache лучше писать так, чтобы он для кода ничем не отличался от интерфейса хранилища.
4) Супер-класс gophermart - не очень удачный паттерн(с учетом того, что на него имеют обратные ссылки все его поля). Рекомендую попробовать написать на него тесты.
5) Очень много всего передается, хранится и возвращается в виде указателей, там где это реально не требуется.

2023-09-04 21:29 UTC, valentinsoe commented on cmd/gophermart/main.go
> +	go s.Serve()
Стоит добавить gracefull shutdown для веб-сервера и опроса внешнего сервиса

2023-09-04 21:29 UTC, valentinsoe commented on internal/db/balance.go
> +	_, err := s.db.ExecContext(ctx, "select * from "+tableNameBalance+";")
Почти все диалекты SQL поддерживают синтаксис CREATE TABLE IF NOT EXISTS..

Во-первых мы любую ошибку трактуем как отсутсвие таблицы, во вторых заставляем sql сервер вычитать всю таблицу

2023-09-04 21:29 UTC, valentinsoe commented on internal/db/orders.go
> +				id bigint NOT NULL,
Номер заказа не является числом, он строка состоящая из цифр.

2023-09-04 21:29 UTC, valentinsoe commented on internal/db/orders.go
> +	if order.UserID == o.UserID {
Не супер критично, но лучше бизнес-логику приложения вынести в отдельный слой, а не иметь ее в слое доступа к БД

2023-09-04 21:29 UTC, valentinsoe commented on internal/db/orders.go
> +	tx, err := s.db.Begin()
Хорошо что ты используешь транзакции.

2023-09-04 21:29 UTC, valentinsoe commented on internal/db/balance.go
> +func (s *StorageDB) GetBalance(userID uint64) (*gophermart.Balance, error) {
Не надо возвращать указатель на структуру. Лучше возвращать саму стркутуру

2023-09-04 21:29 UTC, valentinsoe commented on internal/db/orders.go
> +	orders := make([]*gophermart.Order, 0)
0 лучше не указывать(это значене по умолчанию)

2023-09-04 21:29 UTC, valentinsoe commented on internal/db/orders.go
> +		row := txGetBalance.QueryRowContext(s.ctx, o.UserID)
Не обязательно запрашивать баланс в отдельной операции, чтобы его потом добавить. Можно сделать это одним sql выражением.

2023-09-04 21:29 UTC, valentinsoe commented on internal/gophermart/gophermart.go
> +	Users       *Users
Кажется указатель здесь лишнее.

2023-09-04 21:29 UTC, valentinsoe commented on internal/gophermart/balances.go
> +		bs.mu.Lock()
Иметь кэш в памяти приложения идея в целом хорошая.
Но к сожалению такая наивная реализация - порождает множество проблем.
1) Не ограничен размер памяти
2) Такая работа с Mutex не совсем корректна при одновременных запросах.

2023-09-04 21:29 UTC, valentinsoe commented on internal/gophermart/gophermart.go
> +	}
Только Users и Sessions заслужили место в инициализаторе?:)
Остальные сервисы нет?

2023-09-04 21:29 UTC, valentinsoe commented on internal/gophermart/balances.go
> +		bs.mu.Lock()
Еще аккуратнее выглядит, когда кэш - это просто реализация интерфейса хранилища. То есть клиент не отличает ее от хранилища.

2023-09-04 21:29 UTC, valentinsoe commented on internal/gophermart/queue.go
> +	go func() {
Код обработки сигналов должен быть в main, чтобы также уметь корректно останавливать веб-сервер.

2023-09-04 21:29 UTC, valentinsoe commented on internal/gophermart/queue.go
> +		if count > limit {
Мы же знаем сколько нам БД вернула записей. Зачем нам вруную вести каунтер?

2023-09-04 21:29 UTC, valentinsoe commented on internal/gophermart/queue.go
> +		n := uint32(rand.Intn(10)) + 2 // эмулятор переменного кол-во запросов
Нам в заголовке сервис возвращает, через сколько надо сделать следующий запрос.
Такая логика работы - не учитывает ответа сервера - а просто генерит какие-то случайные числа.

2023-09-04 21:29 UTC, valentinsoe commented on internal/server/server.go
> +		signal.Notify(sig, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)
Работа с сигналами не должна быть здесь.
К тому же - так как завершения горутины мы не ждем, то выполниться или нет этот код - мы не можем предсказать.

2023-09-04 21:29 UTC, valentinsoe commented on internal/server/handlers/balance.go
> +	c, err := h.authCheck(w, r)
Лучше сделать мидлвару проверяющую авторизацию, чем в каждом хендлере ее вызывать.

2023-09-04 21:29 UTC, valentinsoe commented on internal/server/handlers/balance.go
> +	balanceProxy, err := h.gm.GetBalance(user.ID)
Чтобы получить баланс мы сначала авторизуем пользователя(1 поход в БД), потом мы получаем пользователя(2 поход в БД) и только после этого идем таки в базу за балансом.
Хотя явно можно ограничиться 2-мя.

2023-09-04 21:29 UTC, valentinsoe commented on pkg/tool/Luhn.go
> +package tool
Предлагаю пакет так и назвать - luhn.
В go не рекомендую называть пакеты общими словами за которыми может быть стоять что угодно.

2023-09-11 12:20 UTC, Osselnet commented on internal/gophermart/gophermart.go
> +	}
остальным сервисам нужен экземпляр класса для инициализации

2023-09-15 05:47 UTC, valentinsoe approved these changes
Спасибо за исправления.
Не все замечания с прошлого ревью были устранены, но принципиально работу готов принять.

Работа с 429 внешнего сервиса есть, но написана сложнее чем можно бы было:)

2023-09-15 05:47 UTC, valentinsoe commented on internal/client/queue.go
> +		signal.Notify(sig, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)
Лучше обработку сигналов оставить в одном месте. Это ответственность main функции, а не каждого отдельного класса.

2023-09-15 05:47 UTC, valentinsoe commented on internal/client/request.go
> +		fmt.Println("[WARNING] Too many requests detected", string(resp.Body()))
Лучше не использовать fmt.Println, если у нас уже есть логгер

2023-09-15 05:47 UTC, valentinsoe commented on internal/client/queue.go
> +	pool      map[uint64]*gophermart.Order
хранить в map указатели - это лишнее

2023-09-15 05:47 UTC, valentinsoe commented on internal/client/queue.go
> +	pool := make(map[uint64]*gophermart.Order, limit)
len(ors) будет лучше

2023-09-15 05:47 UTC, valentinsoe commented on internal/client/queue.go
> +			g.Go(w.Do)
При таком подходе мы постоянно запускаем множество новых горутин. Подход с worker pool в данном случае будет лучше.

2023-09-15 05:47 UTC, valentinsoe commented on internal/client/queue.go
> +	pool := make(map[uint64]*gophermart.Order, limit)
И зачем нам вообще map, если ключом мы не пользуемся?

2023-09-15 08:05 UTC, merged